### ISSUE TITLE
Feature Request: query items by ID substring (e.g all morphemes starting with m11)

### ISSUE THREAD

**Issue by olzama** [xigt/xigt#55]
It would be convenient to query the corpus by  an ID substring. For example, I might know that, in my corpus, all morphemes whose IDs start with m31, correspond to word31.  Right now, I need to explicitly iterate over all items in the morphemes tier to find all which start with "m31". Would be convenient to just have all items whose IDs start with "m31" (where "m31" is a substring of the actual ID, e.g. "m31.1") returned by a function.

**Comment by olzama** [comment]
Actually, I wonder if this is the same issue: https://github.com/xigt/xigt/issues/15

**Comment by goodmami** [comment]
More or less, yes. Assuming you have an item, such as a morpheme with ID `m31`, and all items in some other tier with `m31.` as the substring are annotation descendants of that morpheme, then you could query item `m31` itself and find all descendants in the desired tier. Here's a few ways to do that:

```python
>>> xc = xigtxml.load('mycorpus.xml')
>>> igt = xc[0]  # or whichever igt you want
>>> # first method, just the items that refer to m31
>>> from xigt import ref
>>> ref.referrers(igt, "m31")
{'alignment': ['m31.1', 'm31.2'], 'content': [], 'segmentation': []}
>>> # second method, all annotation descendants of m31
>>> # (you may need to filter descendants from other tiers, if any)
>>> from xigt import query
>>> list(query.descendants(igt.get_item('m31')))
[(<Tier object (id: m; type: morphemes) ...>, 'alignment', <Tier object (id: g; type: glosses) ...>, [<Item object (id: m31.1) ...>, <Item object (id: m31.2) ...>])]
>>> # third method, all glosses with a m31 as a referent 
>>> from xigt import xigtpath as xp
>>> xp.findall(igt, 'tier[@type="glosses"]/item[referent()/@id="m31"]')
[<Item object (id: m31.1) ...>, <Item object (id: m31.2) ...>]
```

For the third method, note that you could use a simpler form:

```python
>>> xp.findall(igt, 'tier[@type="glosses"]/item[@alignment="m31"]')
```

However that would fail to catch things with more complicated alignment expressions, e.g., if the gloss item had `... alignment="m31[0:3]" ...` because then the `alignment` attribute is not simply `m31`.

**Comment by olzama** [comment]
Thanks!!
